import json
import logging
import uuid

from app.agents.base import AgentResult, BaseAgent
from app.services.claude_service import ClaudeService
from app.services.event_logger import EventLogger

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are a senior code reviewer for an automated bug fix pipeline. You receive a git diff generated by an AI agent and must evaluate it against 4 quality dimensions.

Review the diff and output ONLY valid JSON with this exact structure:
{
  "overall": "approve" | "reject" | "escalate",
  "dimensions": {
    "style": {"score": 0.0-1.0, "notes": "..."},
    "tests": {"score": 0.0-1.0, "notes": "..."},
    "regression": {"score": 0.0-1.0, "notes": "..."},
    "security": {"score": 0.0-1.0, "notes": "..."}
  },
  "confidence": 0.0-1.0,
  "summary": "2-3 sentence review summary"
}

Review dimensions:
1. **Style** — Does the fix follow the existing code style? Naming conventions, formatting, patterns.
2. **Tests** — Are there new or updated tests covering the fix? Are assertions meaningful?
3. **Regression** — Could this change break existing functionality? Are side effects considered?
4. **Security** — No hardcoded secrets, no SQL injection, no XSS, no command injection. Check for OWASP top 10.

Decision rules:
- REJECT if any security dimension score < 0.3 (critical security issue)
- ESCALATE if overall confidence is 0.4-0.6 (uncertain)
- APPROVE if confidence > 0.6 and no critical issues

Output ONLY the JSON, no markdown code fences."""


class CodeReviewerAgent(BaseAgent):
    name = "code_reviewer"

    def __init__(
        self,
        pipeline_run_id: uuid.UUID,
        event_logger: EventLogger,
        claude_service: ClaudeService,
    ):
        super().__init__(pipeline_run_id, event_logger)
        self.claude = claude_service

    async def run(self, context: dict) -> AgentResult:
        diff = context.get("diff", "")
        analysis = context.get("analysis", {})

        await self.log_action("review_diff", {
            "diff_lines": len(diff.splitlines()),
            "problem_statement": analysis.get("problem_statement", "unknown"),
        })

        if not diff.strip():
            await self.log_error("Empty diff — nothing to review")
            return AgentResult(
                success=False,
                error="Empty diff provided for review",
            )

        user_prompt = f"""Original Bug Analysis:
Problem: {analysis.get('problem_statement', 'Not available')}
Severity: {analysis.get('severity', 'unknown')}
Affected files: {', '.join(analysis.get('affected_files', []))}

Generated Fix (git diff):
{diff}"""

        try:
            response = await self.claude.analyze(
                system_prompt=SYSTEM_PROMPT,
                user_prompt=user_prompt,
            )

            review = json.loads(response.strip())

            overall = review.get("overall", "escalate")
            confidence = review.get("confidence", 0.0)
            dimensions = review.get("dimensions", {})

            await self.log_observation(
                f"Review complete: overall={overall}, confidence={confidence}, "
                f"style={dimensions.get('style', {}).get('score', 0)}, "
                f"tests={dimensions.get('tests', {}).get('score', 0)}, "
                f"regression={dimensions.get('regression', {}).get('score', 0)}, "
                f"security={dimensions.get('security', {}).get('score', 0)}"
            )

            # Apply decision rules
            security_score = dimensions.get("security", {}).get("score", 0)
            if security_score < 0.3:
                overall = "reject"
                await self.log_decision(
                    f"Rejecting: critical security issue (score={security_score})",
                    confidence,
                )
            elif 0.4 <= confidence <= 0.6:
                overall = "escalate"
                await self.log_decision(
                    f"Escalating: uncertain confidence ({confidence})",
                    confidence,
                )
            elif confidence > 0.6:
                overall = "approve"
                await self.log_decision(
                    f"Approving: high confidence ({confidence}), no critical issues",
                    confidence,
                )

            success = overall == "approve"
            error = None
            if overall == "reject":
                error = f"Review rejected: {review.get('summary', 'Critical issues found')}"
            elif overall == "escalate":
                error = f"Review uncertain: {review.get('summary', 'Needs human review')}"

            return AgentResult(
                success=success,
                output=review,
                confidence=confidence,
                error=error,
                tokens_used=self.claude.total_tokens_used,
            )

        except json.JSONDecodeError as e:
            await self.log_error(f"Failed to parse review response: {e}")
            return AgentResult(
                success=False,
                error=f"Failed to parse review response: {e}",
                tokens_used=self.claude.total_tokens_used,
            )
        except Exception as e:
            await self.log_error(f"Code reviewer failed: {e}")
            return AgentResult(
                success=False,
                error=str(e),
                tokens_used=self.claude.total_tokens_used,
            )
