import logging
import uuid

from app.agents.base import AgentResult, BaseAgent
from app.services.event_logger import EventLogger
from app.services.github_service import GitHubService
from app.services.slack_service import notify_escalation

logger = logging.getLogger(__name__)


class EscalationHandler(BaseAgent):
    name = "escalation_handler"

    def __init__(self, pipeline_run_id: uuid.UUID, event_logger: EventLogger):
        super().__init__(pipeline_run_id, event_logger)
        self.github = GitHubService()

    async def run(self, context: dict) -> AgentResult:
        return await self.escalate(**context)

    async def escalate(
        self,
        repo_full_name: str,
        issue_number: int,
        github_token: str,
        agent_name: str,
        reason: str,
        partial_analysis: dict | str | None = None,
        slack_webhook_url: str = "",
    ) -> AgentResult:
        await self.log_action("escalate", {
            "repo": repo_full_name,
            "issue_number": issue_number,
            "failing_agent": agent_name,
            "reason": reason,
        })

        # Build the escalation comment
        comment = self._build_comment(agent_name, reason, partial_analysis)

        try:
            await self.github.post_comment(
                repo=repo_full_name,
                issue_number=issue_number,
                comment=comment,
                token=github_token,
            )
            await self.log_observation(
                f"Escalation comment posted on {repo_full_name}#{issue_number}"
            )
            # Send Slack notification if configured
            if slack_webhook_url:
                await notify_escalation(
                    webhook_url=slack_webhook_url,
                    repo_full_name=repo_full_name,
                    issue_number=issue_number,
                    agent_name=agent_name,
                    reason=reason,
                )

            return AgentResult(success=True, output={"comment_posted": True})
        except Exception as e:
            await self.log_error(f"Failed to post escalation comment: {e}")
            return AgentResult(success=False, error=str(e))
        finally:
            await self.github.close()

    def _build_comment(
        self,
        agent_name: str,
        reason: str,
        partial_analysis: dict | str | None,
    ) -> str:
        lines = [
            "## TicketForge — Escalation",
            "",
            f"TicketForge analyzed this ticket but could not generate a confident fix.",
            "",
            f"**Failing step:** `{agent_name}`",
            f"**Reason:** {reason}",
        ]

        if partial_analysis and isinstance(partial_analysis, dict):
            lines.append("")
            lines.append("### Partial Analysis")
            lines.append("")
            if partial_analysis.get("problem_statement"):
                lines.append(f"**Problem:** {partial_analysis['problem_statement']}")
            if partial_analysis.get("affected_files"):
                files = ", ".join(f"`{f}`" for f in partial_analysis["affected_files"])
                lines.append(f"**Affected files:** {files}")
            if partial_analysis.get("severity"):
                lines.append(f"**Severity:** {partial_analysis['severity']}")
            if partial_analysis.get("reproduction_steps"):
                lines.append("")
                lines.append("**Reproduction steps:**")
                for step in partial_analysis["reproduction_steps"]:
                    lines.append(f"- {step}")

        lines.append("")
        lines.append("---")
        lines.append("*This analysis was generated by TicketForge to help the developer who picks up this ticket.*")

        return "\n".join(lines)
